package com.example.thomun.domain.models.home

data class Content(
    val article_id: String,
    val audio_url: String,
    val audiobook_id: String,
    val author_name: String,
    val avatar_url: String,
    val description: String,
    val duration: Int,
    val episode_count: Int,
    val episode_id: String,
    val episode_type: String,
    val free_transcript_url: Any,
    val language: String,
    val name: String,
    val number: Any,
    val paid_early_access_audio_url: Any,
    val paid_early_access_date: Any,
    val paid_exclusive_start_time: Int,
    val paid_exclusivity_type: Any,
    val paid_is_early_access: Boolean,
    val paid_is_exclusive: Boolean,
    val paid_is_exclusive_partially: Boolean,
    val paid_is_now_early_access: Boolean,
    val paid_transcript_url: Any,
    val podcastPopularityScore: Int,
    val podcastPriority: Int,
    val podcast_id: String,
    val podcast_name: String,
    val popularityScore: Int,
    val priority: Int,
    val release_date: String,
    val score: Double,
    val season_number: Any,
    val separated_audio_url: String
)